Tickers:
  - AAPL
  - MSFT
  - GOOG
  - MMM
  - AOS
  - ABT
  - ABBV
  - ACN
  - ADBE
  - AMD
  - AES
  - AFL
  - NVDA
  - AMZN
  - META
  - AVGO
StartDate: '2020-01-01'
EndDate: '2024-12-31'
Interval: 1d
LastDownloadedRows: 1006
RiskPct: 5
RiskRewardRatio: 2
TimeLimit: 5
ATRLookback: 14
ATRMultiplier: 1.0
Equity: 10000
SMAWindows: [15, 50, 200]
EMAWindows: [15, 50, 200]
RSIWindows: [14]
BBParams:
  - {Window: 20, Std: 2}
MFIWindows: [14]
MACDParams:
  - {Fast: 12, Slow: 26, Signal: 9}
LSTMParams:
  Features: ['Close', 'High', 'Low', 'Open', 'Volume', 'MACD_12_26_9','MACDh_12_26_9', 
             'MACDs_12_26_9', 'EMA_15', 'EMA_50', 'EMA_200',
             'SMA_15', 'SMA_50', 'SMA_200', 'RSI_14', 'BBL_20_2.0', 'BBM_20_2.0',
             'BBU_20_2.0', 'BBB_20_2.0', 'BBP_20_2.0', 'MFI_14']
  LabelColumn: Label
  SequenceLength: 5
  BatchSize: 4
  LearningRate: 0.001
  Epochs: 1
  HiddenSize: [16]
  DropoutRate: 0.1
  ModelPath: LSTMModel.pth
ScalerDictPath: ScalerDict.pkl
